---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lynanextjs
  labels:
    app: lynanextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lynanextjs
  template:
    metadata:
      labels:
        app: lynanextjs
    spec:
      containers:
        - name: lynanextjs
          image: docker.io/phengbunath/lynanextjs:1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
